services:
  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-net
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  backend:
    build: 
      context: ./Backend
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    networks:
      - mern-net
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - SECRET=${SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - CLIENT_URL=${CLIENT_URL}

  front:
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-net

volumes:
  mongo-data:

networks:
  mern-net:
    driver: bridge